"""invitations and global email uniqueness

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-19 21:11:29.029710
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# Vector columns render as pgvector types, so the import has to be present in
# every generated script whether or not that script happens to use one.


revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _guard_duplicate_emails() -> None:
    """Refuse to run if any address is already duplicated.

    The unique index below would otherwise fail with a bare constraint
    violation naming no rows. Merging or renaming accounts is a decision for a
    person, not something a migration should do silently, so this stops with
    the conflicting addresses named.
    """
    conflicts = (
        op.get_bind()
        .execute(
            sa.text(
                "SELECT lower(email) AS email, count(*) AS n "
                "FROM users GROUP BY lower(email) HAVING count(*) > 1"
            )
        )
        .fetchall()
    )
    if conflicts:
        listed = ", ".join(f"{row.email} ({row.n} accounts)" for row in conflicts)
        raise RuntimeError(
            "Cannot enforce unique email addresses: these are already "
            f"duplicated — {listed}. Resolve them before migrating; an email "
            "identifies exactly one account."
        )


def upgrade() -> None:
    _guard_duplicate_emails()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invitations",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("invited_by", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "role",
            sa.Enum("org_admin", "team_admin", "member", "viewer", name="role"),
            nullable=False,
        ),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "revoked", "expired", name="invitation_status"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by"],
            ["users.id"],
            name=op.f("fk_invitations_accepted_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_invitations_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_invitations_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_invitations_team_id_teams"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
    )
    op.create_index(op.f("ix_invitations_created_at"), "invitations", ["created_at"], unique=False)
    op.create_index("ix_invitations_email", "invitations", ["email"], unique=False)
    op.create_index(op.f("ix_invitations_org_id"), "invitations", ["org_id"], unique=False)
    op.create_index(op.f("ix_invitations_team_id"), "invitations", ["team_id"], unique=False)
    op.create_index(
        "ix_invitations_team_status", "invitations", ["team_id", "status"], unique=False
    )
    op.create_index(op.f("ix_invitations_token_hash"), "invitations", ["token_hash"], unique=True)
    op.create_index("uq_users_email_lower", "users", [sa.text("lower(email)")], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_invitations_token_hash"), table_name="invitations")
    op.drop_index("ix_invitations_team_status", table_name="invitations")
    op.drop_index(op.f("ix_invitations_team_id"), table_name="invitations")
    op.drop_index(op.f("ix_invitations_org_id"), table_name="invitations")
    op.drop_index("ix_invitations_email", table_name="invitations")
    op.drop_index(op.f("ix_invitations_created_at"), table_name="invitations")
    op.drop_table("invitations")
    # ### end Alembic commands ###

    # Autogenerate creates this enum implicitly with the table but does not
    # drop it, so without this the next upgrade fails with "type already
    # exists".
    op.execute("DROP TYPE IF EXISTS invitation_status")
