"""document classifications

Revision ID: 0005
Revises: 0004
Create Date: 2026-08-19 22:14:28.521910
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# Vector columns render as pgvector types, so the import has to be present in
# every generated script whether or not that script happens to use one.
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_classifications",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("policy", "process", "project", "reference", "other", name="document_kind"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("topics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("supersedes_document_id", sa.UUID(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("model_used", sa.String(length=100), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_classifications_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_document_id"],
            ["documents.id"],
            name=op.f("fk_document_classifications_supersedes_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
            name=op.f("fk_document_classifications_team_id_teams"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_document_classifications_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_classifications")),
    )
    op.create_index(
        op.f("ix_document_classifications_created_at"),
        "document_classifications",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_document_classifications_document_id"),
        "document_classifications",
        ["document_id"],
        unique=True,
    )
    op.create_index(
        "ix_document_classifications_team", "document_classifications", ["team_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_classifications_workspace_id"),
        "document_classifications",
        ["workspace_id"],
        unique=False,
    )
    op.create_index(
        "ix_document_classifications_workspace_kind",
        "document_classifications",
        ["workspace_id", "kind"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_document_classifications_workspace_kind", table_name="document_classifications"
    )
    op.drop_index(
        op.f("ix_document_classifications_workspace_id"), table_name="document_classifications"
    )
    op.drop_index("ix_document_classifications_team", table_name="document_classifications")
    op.drop_index(
        op.f("ix_document_classifications_document_id"), table_name="document_classifications"
    )
    op.drop_index(
        op.f("ix_document_classifications_created_at"), table_name="document_classifications"
    )
    op.drop_table("document_classifications")
    # ### end Alembic commands ###

    # Autogenerate creates the enum implicitly with the table but never drops
    # it, so without this the next upgrade fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS document_kind")
