"""presets: named, shareable system prompts

Revision ID: 0014
Revises: 0013
Create Date: 2026-08-23 07:48:24.924906
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "presets",
        sa.Column("org_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("model_hint", sa.String(length=120), nullable=True),
        sa.Column(
            "scope", sa.Enum("private", "org", "published", name="preset_scope"), nullable=False
        ),
        sa.Column("is_native", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_presets_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_presets_org_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_presets")),
        sa.UniqueConstraint("org_id", "slug", name="uq_presets_org_slug"),
    )
    op.create_index(op.f("ix_presets_created_at"), "presets", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_presets_created_by_user_id"), "presets", ["created_by_user_id"], unique=False
    )
    op.create_index(op.f("ix_presets_org_id"), "presets", ["org_id"], unique=False)
    op.create_index("ix_presets_org_scope", "presets", ["org_id", "scope"], unique=False)
    op.create_index(op.f("ix_presets_slug"), "presets", ["slug"], unique=False)
    op.create_table(
        "preset_pins",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("preset_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["presets.id"],
            name=op.f("fk_preset_pins_preset_id_presets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_preset_pins_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preset_pins")),
        sa.UniqueConstraint("user_id", "preset_id", name="uq_preset_pins_pair"),
    )
    op.create_index(op.f("ix_preset_pins_created_at"), "preset_pins", ["created_at"], unique=False)
    op.create_index(op.f("ix_preset_pins_preset_id"), "preset_pins", ["preset_id"], unique=False)
    op.create_index(op.f("ix_preset_pins_user_id"), "preset_pins", ["user_id"], unique=False)
    op.create_table(
        "preset_shares",
        sa.Column("preset_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("shared_by_user_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["presets.id"],
            name=op.f("fk_preset_shares_preset_id_presets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["shared_by_user_id"],
            ["users.id"],
            name=op.f("fk_preset_shares_shared_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_preset_shares_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_preset_shares")),
        sa.UniqueConstraint("preset_id", "user_id", name="uq_preset_shares_pair"),
    )
    op.create_index(
        op.f("ix_preset_shares_created_at"), "preset_shares", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_preset_shares_preset_id"), "preset_shares", ["preset_id"], unique=False
    )
    op.create_index(op.f("ix_preset_shares_user_id"), "preset_shares", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # --- Row-level security ------------------------------------------------
    # Presets are scoped by organisation rather than workspace, so the existing
    # `avocado.workspace_id` setting says nothing about them. The acting user
    # does: `users.org_id` is the tenant boundary, and this is the second layer
    # behind the repository's own filter.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION avocado_user_org()
        RETURNS uuid
        LANGUAGE sql
        STABLE
        SECURITY DEFINER
        SET search_path = public
        AS $$
            SELECT u.org_id FROM users u
            WHERE u.id = NULLIF(current_setting('avocado.user_id', true), '')::uuid
        $$;
        """
    )

    op.execute("ALTER TABLE presets ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE presets FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON presets
        USING (org_id = avocado_user_org())
        WITH CHECK (org_id = avocado_user_org())
        """
    )

    # Both hang off a preset and inherit its boundary, the same way
    # conversation_tools inherits its conversation's.
    for table in ("preset_pins", "preset_shares"):
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY tenant_isolation ON {table}
            USING (preset_id IN (SELECT id FROM presets))
            WITH CHECK (preset_id IN (SELECT id FROM presets))
            """  # noqa: S608
        )

    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'avocado_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE
                    ON presets, preset_pins, preset_shares TO avocado_app;
                GRANT EXECUTE ON FUNCTION avocado_user_org() TO avocado_app;
            END IF;
        END $$;
        """
    )


def downgrade() -> None:
    for table in ("preset_shares", "preset_pins", "presets"):
        op.execute(f"DROP POLICY IF EXISTS tenant_isolation ON {table}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_preset_shares_user_id"), table_name="preset_shares")
    op.drop_index(op.f("ix_preset_shares_preset_id"), table_name="preset_shares")
    op.drop_index(op.f("ix_preset_shares_created_at"), table_name="preset_shares")
    op.drop_table("preset_shares")
    op.drop_index(op.f("ix_preset_pins_user_id"), table_name="preset_pins")
    op.drop_index(op.f("ix_preset_pins_preset_id"), table_name="preset_pins")
    op.drop_index(op.f("ix_preset_pins_created_at"), table_name="preset_pins")
    op.drop_table("preset_pins")
    op.drop_index(op.f("ix_presets_slug"), table_name="presets")
    op.drop_index("ix_presets_org_scope", table_name="presets")
    op.drop_index(op.f("ix_presets_org_id"), table_name="presets")
    op.drop_index(op.f("ix_presets_created_by_user_id"), table_name="presets")
    op.drop_index(op.f("ix_presets_created_at"), table_name="presets")
    op.drop_table("presets")
    op.execute("DROP FUNCTION IF EXISTS avocado_user_org()")
    # Dropping the tables does not drop the type. Without this, a downgrade
    # followed by an upgrade fails on CREATE TYPE — which is exactly the path a
    # rollback takes.
    op.execute("DROP TYPE IF EXISTS preset_scope")
    # ### end Alembic commands ###
