"""message preset provenance

Revision ID: 0015
Revises: 0014
Create Date: 2026-08-23 08:00:18.566549
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("messages", sa.Column("preset_id", sa.UUID(), nullable=True))
    op.add_column("messages", sa.Column("preset_version", sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f("fk_messages_preset_id_presets"),
        "messages",
        "presets",
        ["preset_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_messages_preset_id_presets"), "messages", type_="foreignkey")
    op.drop_column("messages", "preset_version")
    op.drop_column("messages", "preset_id")
    # ### end Alembic commands ###
