"""conversation pinned and archived

Revision ID: 0016
Revises: 0015
Create Date: 2026-08-23 08:15:51.292811
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` is required, not cosmetic: adding a NOT NULL column to a
    # table that already has rows fails outright without one. It is dropped
    # again below so the application stays the only thing deciding the value.
    op.add_column(
        "conversations",
        sa.Column("pinned", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "conversations",
        sa.Column("archived", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("conversations", "pinned", server_default=None)
    op.alter_column("conversations", "archived", server_default=None)
    op.create_index(op.f("ix_conversations_archived"), "conversations", ["archived"], unique=False)
    op.create_index(op.f("ix_conversations_pinned"), "conversations", ["pinned"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_conversations_pinned"), table_name="conversations")
    op.drop_index(op.f("ix_conversations_archived"), table_name="conversations")
    op.drop_column("conversations", "archived")
    op.drop_column("conversations", "pinned")
    # ### end Alembic commands ###
