"""message feedback

Revision ID: 0017
Revises: 0016
Create Date: 2026-08-23 08:21:47.183812
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_feedback",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.Enum("up", "down", name="feedback_rating"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_feedback_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_message_feedback_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_feedback")),
        sa.UniqueConstraint("message_id", "user_id", name="uq_message_feedback_pair"),
    )
    op.create_index(
        op.f("ix_message_feedback_created_at"), "message_feedback", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_message_id"), "message_feedback", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_feedback_user_id"), "message_feedback", ["user_id"], unique=False
    )
    op.execute("ALTER TABLE message_feedback ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE message_feedback FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON message_feedback
        USING (message_id IN (SELECT id FROM messages))
        WITH CHECK (message_id IN (SELECT id FROM messages))
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'avocado_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON message_feedback TO avocado_app;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON message_feedback")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_feedback_user_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_message_id"), table_name="message_feedback")
    op.drop_index(op.f("ix_message_feedback_created_at"), table_name="message_feedback")
    op.drop_table("message_feedback")
    # Dropping the table does not drop the type. Without this a downgrade
    # followed by an upgrade dies on CREATE TYPE — the exact path a rollback
    # takes. Same defect as 0014; caught the same way, by running it.
    op.execute("DROP TYPE IF EXISTS feedback_rating")
    # ### end Alembic commands ###
