"""schedules

Revision ID: 0018
Revises: 0017
Create Date: 2026-08-23 08:46:27.065937
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedules",
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("preset_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("cron", sa.String(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_schedules_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["preset_id"],
            ["presets.id"],
            name=op.f("fk_schedules_preset_id_presets"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_schedules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedules")),
    )
    op.create_index(op.f("ix_schedules_created_at"), "schedules", ["created_at"], unique=False)
    op.create_index("ix_schedules_due", "schedules", ["enabled", "next_run_at"], unique=False)
    op.create_index(op.f("ix_schedules_next_run_at"), "schedules", ["next_run_at"], unique=False)
    op.create_index(
        "ix_schedules_workspace", "schedules", ["workspace_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_schedules_workspace_id"), "schedules", ["workspace_id"], unique=False)
    op.execute("ALTER TABLE schedules ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE schedules FORCE ROW LEVEL SECURITY")
    op.execute(
        """
        CREATE POLICY tenant_isolation ON schedules
        USING (
            workspace_id = NULLIF(current_setting('avocado.workspace_id', true), '')::uuid
            OR workspace_id IN (SELECT avocado_visible_workspaces())
        )
        WITH CHECK (
            workspace_id = NULLIF(current_setting('avocado.workspace_id', true), '')::uuid
            OR workspace_id IN (SELECT avocado_visible_workspaces())
        )
        """
    )
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'avocado_app') THEN
                GRANT SELECT, INSERT, UPDATE, DELETE ON schedules TO avocado_app;
            END IF;
        END $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP POLICY IF EXISTS tenant_isolation ON schedules")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_schedules_workspace_id"), table_name="schedules")
    op.drop_index("ix_schedules_workspace", table_name="schedules")
    op.drop_index(op.f("ix_schedules_next_run_at"), table_name="schedules")
    op.drop_index("ix_schedules_due", table_name="schedules")
    op.drop_index(op.f("ix_schedules_created_at"), table_name="schedules")
    op.drop_table("schedules")
    # ### end Alembic commands ###
